### ISSUE TITLE
Check ZDO Request: ZDO_MGMT_PERMIT_JOIN_REQ

### ISSUE THREAD

**Issue by simenkid** [jackchased/cc-znp#2]
**ZigBee MT Cmd**: ZDO_MGMT_PERMIT_JOIN_REQ
**cc-znp CmdId**: mgmtPermitJoinReq
**Arguments**: `{ dstaddr, duration, tcsignificance }`

But MT-API guide says the argument should be:  `{ addrmode, dstaddr, duration, tcsignificance }`
  
  
![image](https://cloud.githubusercontent.com/assets/7709608/15386579/25c65222-1ddb-11e6-9a7e-4761edc283af.png)

**Comment by simenkid** [comment]
In ZStack-CC2530-2.5.1a

I believe in Z-Stack Home 1.2.1, the arguments are changed.

![image](https://cloud.githubusercontent.com/assets/7709608/15386852/92d2a9aa-1ddc-11e6-9e43-414bb892a743.png)

**Comment by jackchased** [comment]
I add the argument `addrmode` to the *mgmtPermitJoinReq* command, thanks.
